// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: proto/chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BroadcastClient is the client API for Broadcast service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BroadcastClient interface {
	CreateGroupStream(ctx context.Context, in *CreateGroup, opts ...grpc.CallOption) (Broadcast_CreateGroupStreamClient, error)
	DirectMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (Broadcast_DirectMessageClient, error)
	JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (Broadcast_JoinGroupClient, error)
	Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*LoginRes, error)
	ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersRes, error)
	BroadcastMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Shutdown, error)
}

type broadcastClient struct {
	cc grpc.ClientConnInterface
}

func NewBroadcastClient(cc grpc.ClientConnInterface) BroadcastClient {
	return &broadcastClient{cc}
}

func (c *broadcastClient) CreateGroupStream(ctx context.Context, in *CreateGroup, opts ...grpc.CallOption) (Broadcast_CreateGroupStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Broadcast_ServiceDesc.Streams[0], "/chat.Broadcast/CreateGroupStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &broadcastCreateGroupStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broadcast_CreateGroupStreamClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type broadcastCreateGroupStreamClient struct {
	grpc.ClientStream
}

func (x *broadcastCreateGroupStreamClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *broadcastClient) DirectMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (Broadcast_DirectMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &Broadcast_ServiceDesc.Streams[1], "/chat.Broadcast/DirectMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &broadcastDirectMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broadcast_DirectMessageClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type broadcastDirectMessageClient struct {
	grpc.ClientStream
}

func (x *broadcastDirectMessageClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *broadcastClient) JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (Broadcast_JoinGroupClient, error) {
	stream, err := c.cc.NewStream(ctx, &Broadcast_ServiceDesc.Streams[2], "/chat.Broadcast/JoinGroup", opts...)
	if err != nil {
		return nil, err
	}
	x := &broadcastJoinGroupClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broadcast_JoinGroupClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type broadcastJoinGroupClient struct {
	grpc.ClientStream
}

func (x *broadcastJoinGroupClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *broadcastClient) Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, "/chat.Broadcast/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *broadcastClient) ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersRes, error) {
	out := new(ListUsersRes)
	err := c.cc.Invoke(ctx, "/chat.Broadcast/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *broadcastClient) BroadcastMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Shutdown, error) {
	out := new(Shutdown)
	err := c.cc.Invoke(ctx, "/chat.Broadcast/BroadcastMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BroadcastServer is the server API for Broadcast service.
// All implementations must embed UnimplementedBroadcastServer
// for forward compatibility
type BroadcastServer interface {
	CreateGroupStream(*CreateGroup, Broadcast_CreateGroupStreamServer) error
	DirectMessage(*Message, Broadcast_DirectMessageServer) error
	JoinGroup(*JoinGroupReq, Broadcast_JoinGroupServer) error
	Login(context.Context, *User) (*LoginRes, error)
	ListUsers(context.Context, *ListUsersReq) (*ListUsersRes, error)
	BroadcastMessage(context.Context, *Message) (*Shutdown, error)
	mustEmbedUnimplementedBroadcastServer()
}

// UnimplementedBroadcastServer must be embedded to have forward compatible implementations.
type UnimplementedBroadcastServer struct {
}

func (UnimplementedBroadcastServer) CreateGroupStream(*CreateGroup, Broadcast_CreateGroupStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateGroupStream not implemented")
}
func (UnimplementedBroadcastServer) DirectMessage(*Message, Broadcast_DirectMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method DirectMessage not implemented")
}
func (UnimplementedBroadcastServer) JoinGroup(*JoinGroupReq, Broadcast_JoinGroupServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinGroup not implemented")
}
func (UnimplementedBroadcastServer) Login(context.Context, *User) (*LoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBroadcastServer) ListUsers(context.Context, *ListUsersReq) (*ListUsersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedBroadcastServer) BroadcastMessage(context.Context, *Message) (*Shutdown, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastMessage not implemented")
}
func (UnimplementedBroadcastServer) mustEmbedUnimplementedBroadcastServer() {}

// UnsafeBroadcastServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BroadcastServer will
// result in compilation errors.
type UnsafeBroadcastServer interface {
	mustEmbedUnimplementedBroadcastServer()
}

func RegisterBroadcastServer(s grpc.ServiceRegistrar, srv BroadcastServer) {
	s.RegisterService(&Broadcast_ServiceDesc, srv)
}

func _Broadcast_CreateGroupStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateGroup)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BroadcastServer).CreateGroupStream(m, &broadcastCreateGroupStreamServer{stream})
}

type Broadcast_CreateGroupStreamServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type broadcastCreateGroupStreamServer struct {
	grpc.ServerStream
}

func (x *broadcastCreateGroupStreamServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Broadcast_DirectMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Message)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BroadcastServer).DirectMessage(m, &broadcastDirectMessageServer{stream})
}

type Broadcast_DirectMessageServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type broadcastDirectMessageServer struct {
	grpc.ServerStream
}

func (x *broadcastDirectMessageServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Broadcast_JoinGroup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinGroupReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BroadcastServer).JoinGroup(m, &broadcastJoinGroupServer{stream})
}

type Broadcast_JoinGroupServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type broadcastJoinGroupServer struct {
	grpc.ServerStream
}

func (x *broadcastJoinGroupServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Broadcast_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Broadcast/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastServer).Login(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broadcast_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Broadcast/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastServer).ListUsers(ctx, req.(*ListUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broadcast_BroadcastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastServer).BroadcastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Broadcast/BroadcastMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastServer).BroadcastMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// Broadcast_ServiceDesc is the grpc.ServiceDesc for Broadcast service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broadcast_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Broadcast",
	HandlerType: (*BroadcastServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Broadcast_Login_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Broadcast_ListUsers_Handler,
		},
		{
			MethodName: "BroadcastMessage",
			Handler:    _Broadcast_BroadcastMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateGroupStream",
			Handler:       _Broadcast_CreateGroupStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DirectMessage",
			Handler:       _Broadcast_DirectMessage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "JoinGroup",
			Handler:       _Broadcast_JoinGroup_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/chat.proto",
}
